Repository dnd-side-project/dnd-11th-3-backend, pull requests merged in 2024-11, with the labels that each got.

#118 [feat #117] 회원 탈퇴 API
  src/main/java/com/dnd/gongmuin/answer/domain/Answer.java
  src/main/java/com/dnd/gongmuin/answer/repository/AnswerRepository.java
  src/main/java/com/dnd/gongmuin/auth/controller/AuthController.java
  src/main/java/com/dnd/gongmuin/auth/dto/response/DeleteMemberResponse.java
  src/main/java/com/dnd/gongmuin/auth/service/AuthService.java
  src/main/java/com/dnd/gongmuin/common/config/RestTemplateConfig.java
  src/main/java/com/dnd/gongmuin/credit_history/repository/CreditHistoryRepository.java
  src/main/java/com/dnd/gongmuin/member/exception/MemberErrorCode.java
  src/main/java/com/dnd/gongmuin/member/repository/MemberRepository.java
  src/main/java/com/dnd/gongmuin/member/service/MemberService.java
  src/main/java/com/dnd/gongmuin/notification/repository/NotificationRepository.java
  src/main/java/com/dnd/gongmuin/post_interaction/repository/InteractionRepository.java
  src/main/java/com/dnd/gongmuin/question_post/domain/QuestionPost.java
  src/main/java/com/dnd/gongmuin/question_post/repository/QuestionPostRepository.java
  src/main/java/com/dnd/gongmuin/security/exception/OAuth2ErrorCode.java
  src/main/java/com/dnd/gongmuin/security/jwt/util/TokenAuthenticationFilter.java
  src/main/java/com/dnd/gongmuin/security/jwt/util/TokenProvider.java
  src/main/java/com/dnd/gongmuin/security/oauth2/KakaoResponse.java
  src/main/java/com/dnd/gongmuin/security/oauth2/NaverResponse.java
  src/main/java/com/dnd/gongmuin/security/oauth2/Oauth2Response.java
  src/main/java/com/dnd/gongmuin/security/service/CustomOauth2UserService.java
  src/main/java/com/dnd/gongmuin/security/service/OAuth2UnlinkService.java
  src/test/java/com/dnd/gongmuin/auth/controller/AuthControllerTest.java
  src/test/java/com/dnd/gongmuin/auth/service/AuthServiceTest.java
  src/test/java/com/dnd/gongmuin/common/fixture/MemberFixture.java
  src/test/java/com/dnd/gongmuin/member/service/MemberServiceTest.java
  src/test/java/com/dnd/gongmuin/security/jwt/TokenProviderTest.java
Labels: ✨ feat

#137 [feat #136] 채팅방 상세 조회 응답에 요청자 여부 필드 추가
  src/main/java/com/dnd/gongmuin/chat/dto/ChatRoomMapper.java
  src/main/java/com/dnd/gongmuin/chat/dto/response/ChatRoomDetailResponse.java
  src/test/java/com/dnd/gongmuin/chat/controller/ChatRoomControllerTest.java
Labels: ✨ feat

#139 [feat #138] 채팅방 목록 조회 API 상태 필드 추가 및 필터링 수정
  src/main/java/com/dnd/gongmuin/answer/repository/AnswerRepository.java
  src/main/java/com/dnd/gongmuin/auth/service/AuthService.java
  src/main/java/com/dnd/gongmuin/chat/controller/ChatRoomController.java
  src/main/java/com/dnd/gongmuin/chat/domain/ChatStatus.java
  src/main/java/com/dnd/gongmuin/chat/dto/ChatRoomMapper.java
  src/main/java/com/dnd/gongmuin/chat/dto/response/ChatRoomInfo.java
  src/main/java/com/dnd/gongmuin/chat/dto/response/ChatRoomSimpleResponse.java
  src/main/java/com/dnd/gongmuin/chat/repository/ChatRoomQueryRepository.java
  src/main/java/com/dnd/gongmuin/chat/repository/ChatRoomQueryRepositoryImpl.java
  src/main/java/com/dnd/gongmuin/chat/service/ChatRoomService.java
  src/main/java/com/dnd/gongmuin/member/repository/MemberRepository.java
  src/main/java/com/dnd/gongmuin/notification/repository/NotificationRepository.java
  src/main/java/com/dnd/gongmuin/question_post/repository/QuestionPostRepository.java
  src/test/java/com/dnd/gongmuin/auth/service/AuthServiceTest.java
  src/test/java/com/dnd/gongmuin/chat/controller/ChatRoomControllerTest.java
  src/test/java/com/dnd/gongmuin/chat/repository/ChatRoomRepositoryTest.java
  src/test/java/com/dnd/gongmuin/chat/service/ChatRoomServiceTest.java
  src/test/java/com/dnd/gongmuin/credit_history/service/CreditHistoryServiceTest.java
  src/test/java/com/dnd/gongmuin/member/repository/MemberRepositoryTest.java
Labels: ✨ feat

#145 [feat] : 채팅 요청 필드명 수정
  src/main/java/com/dnd/gongmuin/chat_inquiry/domain/ChatInquiry.java
  src/main/java/com/dnd/gongmuin/chat_inquiry/dto/CreateChatInquiryRequest.java
  src/main/java/com/dnd/gongmuin/chat_inquiry/service/ChatInquiryService.java
Labels: ✨ feat

#147 [feat #146] 채팅 상세조회 응답 dto 필드명 수정
  src/main/java/com/dnd/gongmuin/chat_inquiry/domain/ChatInquiry.java
  src/main/java/com/dnd/gongmuin/chat_inquiry/dto/ChatInquiryResponse.java
  src/main/java/com/dnd/gongmuin/chat_inquiry/dto/CreateChatInquiryResponse.java
  src/main/java/com/dnd/gongmuin/chatroom/controller/ChatRoomController.java
  src/main/java/com/dnd/gongmuin/chatroom/dto/response/ChatRoomDetailResponse.java
  src/test/java/com/dnd/gongmuin/chat/controller/ChatRoomControllerTest.java
  src/test/java/com/dnd/gongmuin/chat/service/ChatRoomServiceTest.java
  src/test/java/com/dnd/gongmuin/chat_inquiry/controller/ChatInquiryControllerTest.java
  src/test/java/com/dnd/gongmuin/chat_inquiry/repository/ChatInquiryRepositoryTest.java
  src/test/java/com/dnd/gongmuin/chat_inquiry/service/ChatInquiryServiceTest.java
Labels: ✨ feat

#150 [feat #149] 채팅 요청 수락 시 채팅 요청 메시지를 채팅방 메시지에 저장
  src/main/java/com/dnd/gongmuin/chat_inquiry/domain/ChatInquiry.java
  src/main/java/com/dnd/gongmuin/chat_inquiry/domain/InquiryStatus.java
  src/main/java/com/dnd/gongmuin/chat_inquiry/exception/ChatInquiryErrorCode.java
  src/main/java/com/dnd/gongmuin/chat_inquiry/service/ChatInquiryService.java
  src/main/java/com/dnd/gongmuin/chatroom/dto/ChatMessageMapper.java
  src/main/java/com/dnd/gongmuin/chatroom/exception/ChatErrorCode.java
  src/main/java/com/dnd/gongmuin/chatroom/service/ChatRoomService.java
  src/main/java/com/dnd/gongmuin/member/domain/Member.java
  src/test/java/com/dnd/gongmuin/chat_inquiry/service/ChatInquiryServiceTest.java
Labels: ✨ feat

#157 [refactor #156] 채팅 요청 목록 API에서 채팅 파트너 조회 로직 리팩토링
  src/main/java/com/dnd/gongmuin/chat_inquiry/dto/ChatInquiryResponse.java
  src/main/java/com/dnd/gongmuin/chat_inquiry/repository/ChatInquiryQueryRepositoryImpl.java
  src/test/java/com/dnd/gongmuin/chat_inquiry/service/ChatInquiryServiceTest.java
  src/test/java/com/dnd/gongmuin/common/fixture/ChatInquiryFixture.java
Labels: ♻️ refactor

#160 [feat #153] 채팅 요청 자동 거절 알림 생성
  src/main/java/com/dnd/gongmuin/chat_inquiry/dto/RejectedChatInquiryDto.java
  src/main/java/com/dnd/gongmuin/chat_inquiry/repository/ChatInquiryQueryRepository.java
  src/main/java/com/dnd/gongmuin/chat_inquiry/repository/ChatInquiryQueryRepositoryImpl.java
  src/main/java/com/dnd/gongmuin/chat_inquiry/service/ChatInquiryService.java
  src/main/java/com/dnd/gongmuin/notification/domain/NotificationType.java
  src/test/java/com/dnd/gongmuin/chat_inquiry/service/ChatInquiryServiceTest.java
Labels: ✨ feat

#162 [fix #161] 채팅 요청 시 크레딧 감소 안되는 오류 해결
  src/main/java/com/dnd/gongmuin/chat_inquiry/dto/ChatInquiryMapper.java
  src/main/java/com/dnd/gongmuin/chat_inquiry/dto/CreateChatInquiryResponse.java
  src/main/java/com/dnd/gongmuin/chat_inquiry/service/ChatInquiryService.java
  src/test/java/com/dnd/gongmuin/chat_inquiry/controller/ChatInquiryControllerTest.java
Labels: 🚨 fix
