Repository dnd-side-project/dnd-11th-3-backend, pull requests merged in 2024-08, with the labels that each got.

#10 [feat] : 파일 업로드 API 구현
  build.gradle
  src/main/java/com/dnd/gongmuin/common/config/JpaAuditingConfig.java
  src/main/java/com/dnd/gongmuin/common/config/S3Config.java
  src/main/java/com/dnd/gongmuin/s3/controller/S3Controller.java
  src/main/java/com/dnd/gongmuin/s3/dto/ImagesUploadRequest.java
  src/main/java/com/dnd/gongmuin/s3/dto/ImagesUploadResponse.java
  src/main/java/com/dnd/gongmuin/s3/dto/VideoUploadRequest.java
  src/main/java/com/dnd/gongmuin/s3/dto/VideoUploadResponse.java
  src/main/java/com/dnd/gongmuin/s3/exception/S3ErrorCode.java
  src/main/java/com/dnd/gongmuin/s3/service/S3Service.java
Labels: ✨ feat

#15 [fix] : test 경로에 설정 파일 추가
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .gitignore
Labels: 🚨 fix

#13 [feat #4] : 시큐리티 세팅 및 소셜 로그인 API 구현
  build.gradle
  src/main/java/com/dnd/gongmuin/auth/cotroller/AuthController.java
  src/main/java/com/dnd/gongmuin/auth/domain/Auth.java
  src/main/java/com/dnd/gongmuin/auth/domain/AuthStatus.java
  src/main/java/com/dnd/gongmuin/auth/domain/Provider.java
  src/main/java/com/dnd/gongmuin/auth/exception/AuthErrorCode.java
  src/main/java/com/dnd/gongmuin/auth/repository/AuthRepository.java
  src/main/java/com/dnd/gongmuin/auth/service/AuthService.java
  src/main/java/com/dnd/gongmuin/common/exception/runtime/CustomJwtException.java
  src/main/java/com/dnd/gongmuin/member/controller/MemberController.java
  src/main/java/com/dnd/gongmuin/member/domain/Member.java
  src/main/java/com/dnd/gongmuin/member/dto/request/AdditionalInfoRequest.java
  src/main/java/com/dnd/gongmuin/member/dto/request/ValidateNickNameRequest.java
  src/main/java/com/dnd/gongmuin/member/dto/response/SignUpResponse.java
  src/main/java/com/dnd/gongmuin/member/dto/response/ValidateNickNameResponse.java
  src/main/java/com/dnd/gongmuin/member/exception/MemberErrorCode.java
  src/main/java/com/dnd/gongmuin/member/repository/MemberRepository.java
  src/main/java/com/dnd/gongmuin/member/service/MemberService.java
  src/main/java/com/dnd/gongmuin/security/config/SecurityConfig.java
  src/main/java/com/dnd/gongmuin/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/dnd/gongmuin/security/handler/CustomOauth2FailureHandler.java
  src/main/java/com/dnd/gongmuin/security/handler/CustomOauth2SuccessHandler.java
  src/main/java/com/dnd/gongmuin/security/jwt/exception/JwtErrorCode.java
  src/main/java/com/dnd/gongmuin/security/jwt/util/TokenAuthenticationFilter.java
  src/main/java/com/dnd/gongmuin/security/jwt/util/TokenExceptionFilter.java
  src/main/java/com/dnd/gongmuin/security/jwt/util/TokenProvider.java
  src/main/java/com/dnd/gongmuin/security/oauth2/AuthInfo.java
  src/main/java/com/dnd/gongmuin/security/oauth2/CustomOauth2User.java
  src/main/java/com/dnd/gongmuin/security/oauth2/KakaoResponse.java
  src/main/java/com/dnd/gongmuin/security/oauth2/Oauth2Response.java
  src/main/java/com/dnd/gongmuin/security/service/CustomOauth2UserService.java
  src/main/java/com/dnd/gongmuin/security/service/TokenService.java
  src/test/java/com/dnd/gongmuin/GongMuInTestApplication.java
  src/test/java/com/dnd/gongmuin/auth/service/AuthServiceTest.java
  src/test/java/com/dnd/gongmuin/common/fixture/MemberFixture.java
  src/test/java/com/dnd/gongmuin/common/support/ApiTestSupport.java
  src/test/java/com/dnd/gongmuin/member/domain/MemberTest.java
  src/test/java/com/dnd/gongmuin/member/repository/MemberRepositoryTest.java
  src/test/java/com/dnd/gongmuin/member/service/MemberServiceTest.java
  src/test/java/com/dnd/gongmuin/security/jwt/TokenProviderTest.java
Labels: ✨ feat, ⚙️ chore

#17 [feat #16] : 질문 게시글 등록, 상세조회
  .github/workflows/ci.yml
  build.gradle
  src/main/java/com/dnd/gongmuin/common/config/RedisConfig.java
  src/main/java/com/dnd/gongmuin/question_post/controller/QuestionPostController.java
  src/main/java/com/dnd/gongmuin/question_post/domain/QuestionCategory.java
  src/main/java/com/dnd/gongmuin/question_post/domain/QuestionPost.java
  src/main/java/com/dnd/gongmuin/question_post/domain/QuestionPostImage.java
  src/main/java/com/dnd/gongmuin/question_post/dto/MemberInfo.java
  src/main/java/com/dnd/gongmuin/question_post/dto/QuestionPostDetailResponse.java
  src/main/java/com/dnd/gongmuin/question_post/dto/QuestionPostMapper.java
  src/main/java/com/dnd/gongmuin/question_post/dto/RegisterQuestionPostRequest.java
  src/main/java/com/dnd/gongmuin/question_post/exception/QuestionPostErrorCode.java
  src/main/java/com/dnd/gongmuin/question_post/repository/QuestionPostRepository.java
  src/main/java/com/dnd/gongmuin/question_post/service/QuestionPostService.java
  src/main/java/com/dnd/gongmuin/s3/exception/S3ErrorCode.java
  src/test/java/com/dnd/gongmuin/common/fixture/MemberFixture.java
  src/test/java/com/dnd/gongmuin/common/fixture/QuestionPostFixture.java
  src/test/java/com/dnd/gongmuin/common/support/ApiTestSupport.java
  src/test/java/com/dnd/gongmuin/common/support/TestContainerSupport.java
  src/test/java/com/dnd/gongmuin/question_post/controller/QuestionPostControllerTest.java
  src/test/java/com/dnd/gongmuin/question_post/service/QuestionPostServiceTest.java
Labels: ✨ feat

#19 [chore #18] : Swagger 세팅
  build.gradle
  src/main/java/com/dnd/gongmuin/common/config/SwaggerConfig.java
  src/main/java/com/dnd/gongmuin/question_post/controller/QuestionPostController.java
  src/main/java/com/dnd/gongmuin/security/config/SecurityConfig.java
Labels: ⚙️ chore

#22 [feat #21] : 답변 등록/조회 API
  src/main/java/com/dnd/gongmuin/answer/controller/AnswerController.java
  src/main/java/com/dnd/gongmuin/answer/domain/Answer.java
  src/main/java/com/dnd/gongmuin/answer/dto/AnswerDetailResponse.java
  src/main/java/com/dnd/gongmuin/answer/dto/AnswerMapper.java
  src/main/java/com/dnd/gongmuin/answer/dto/RegisterAnswerRequest.java
  src/main/java/com/dnd/gongmuin/answer/repository/AnswerRepository.java
  src/main/java/com/dnd/gongmuin/answer/service/AnswerService.java
  src/main/java/com/dnd/gongmuin/common/dto/PageMapper.java
  src/main/java/com/dnd/gongmuin/common/dto/PageResponse.java
  src/main/java/com/dnd/gongmuin/question_post/domain/QuestionPost.java
  src/main/java/com/dnd/gongmuin/question_post/exception/QuestionPostErrorCode.java
  src/main/java/com/dnd/gongmuin/question_post/repository/QuestionPostRepository.java
  src/main/java/com/dnd/gongmuin/question_post/service/QuestionPostService.java
  src/main/java/com/dnd/gongmuin/security/jwt/util/TokenAuthenticationFilter.java
  src/main/java/com/dnd/gongmuin/security/jwt/util/TokenProvider.java
  src/test/java/com/dnd/gongmuin/answer/controller/AnswerControllerTest.java
  src/test/java/com/dnd/gongmuin/answer/service/AnswerServiceTest.java
  src/test/java/com/dnd/gongmuin/common/fixture/AnswerFixture.java
  src/test/java/com/dnd/gongmuin/common/fixture/MemberFixture.java
  src/test/java/com/dnd/gongmuin/common/fixture/QuestionPostFixture.java
  src/test/java/com/dnd/gongmuin/common/support/TestContainerSupport.java
  src/test/java/com/dnd/gongmuin/question_post/controller/QuestionPostControllerTest.java
  src/test/java/com/dnd/gongmuin/question_post/service/QuestionPostServiceTest.java
Labels: ✨ feat

#25 [feat #20] : 공무원 이메일 인증 API
  build.gradle
  src/main/java/com/dnd/gongmuin/auth/exception/AuthErrorCode.java
  src/main/java/com/dnd/gongmuin/common/config/MailConfig.java
  src/main/java/com/dnd/gongmuin/mail/controller/MailController.java
  src/main/java/com/dnd/gongmuin/mail/dto/MailMapper.java
  src/main/java/com/dnd/gongmuin/mail/dto/request/AuthCodeRequest.java
  src/main/java/com/dnd/gongmuin/mail/dto/request/SendMailRequest.java
  src/main/java/com/dnd/gongmuin/mail/dto/response/AuthCodeResponse.java
  src/main/java/com/dnd/gongmuin/mail/dto/response/SendMailResponse.java
  src/main/java/com/dnd/gongmuin/mail/exception/MailErrorCode.java
  src/main/java/com/dnd/gongmuin/mail/service/MailService.java
  src/main/java/com/dnd/gongmuin/mail/util/AuthCodeGenerator.java
  src/main/java/com/dnd/gongmuin/member/repository/MemberRepository.java
  src/main/java/com/dnd/gongmuin/member/service/MemberService.java
  src/main/java/com/dnd/gongmuin/redis/exception/RedisErrorCode.java
  src/main/java/com/dnd/gongmuin/redis/util/RedisUtil.java
  src/test/java/com/dnd/gongmuin/common/support/ApiTestSupport.java
  src/test/java/com/dnd/gongmuin/mail/controller/MailControllerTest.java
  src/test/java/com/dnd/gongmuin/mail/service/MailServiceTest.java
Labels: ✨ feat

#24 [feat #23] : 답변 채택 API
  src/main/java/com/dnd/gongmuin/answer/controller/AnswerController.java
  src/main/java/com/dnd/gongmuin/answer/domain/Answer.java
  src/main/java/com/dnd/gongmuin/answer/dto/RegisterAnswerRequest.java
  src/main/java/com/dnd/gongmuin/answer/exception/AnswerErrorCode.java
  src/main/java/com/dnd/gongmuin/answer/service/AnswerService.java
  src/main/java/com/dnd/gongmuin/credit/CreditDetail.java
  src/main/java/com/dnd/gongmuin/credit_history/CreditHistory.java
  src/main/java/com/dnd/gongmuin/credit_history/CreditType.java
  src/main/java/com/dnd/gongmuin/credit_history/dto/CreditHistoryMapper.java
  src/main/java/com/dnd/gongmuin/credit_history/repository/CreditHistoryRepository.java
  src/main/java/com/dnd/gongmuin/credit_history/service/CreditHistoryService.java
  src/main/java/com/dnd/gongmuin/member/domain/Member.java
  src/main/java/com/dnd/gongmuin/member/exception/MemberErrorCode.java
  src/main/java/com/dnd/gongmuin/question_post/controller/QuestionPostController.java
  src/main/java/com/dnd/gongmuin/question_post/domain/QuestionPost.java
  src/main/java/com/dnd/gongmuin/question_post/exception/QuestionPostErrorCode.java
  src/main/java/com/dnd/gongmuin/question_post/service/QuestionPostService.java
  src/test/java/com/dnd/gongmuin/answer/controller/AnswerControllerTest.java
  src/test/java/com/dnd/gongmuin/answer/service/AnswerServiceTest.java
  src/test/java/com/dnd/gongmuin/common/fixture/QuestionPostFixture.java
  src/test/java/com/dnd/gongmuin/credit_history/fixture/CreditHistoryFixture.java
  src/test/java/com/dnd/gongmuin/credit_history/service/CreditHistoryServiceTest.java
  src/test/java/com/dnd/gongmuin/question_post/controller/QuestionPostControllerTest.java
Labels: ✨ feat

#28 [Feat #26] JWT 관리(저장/재발급) 및 로그아웃 API
  src/main/java/com/dnd/gongmuin/auth/cotroller/AuthController.java
  src/main/java/com/dnd/gongmuin/auth/domain/Provider.java
  src/main/java/com/dnd/gongmuin/auth/exception/AuthErrorCode.java
  src/main/java/com/dnd/gongmuin/auth/service/AuthService.java
  src/main/java/com/dnd/gongmuin/mail/service/MailService.java
  src/main/java/com/dnd/gongmuin/member/controller/MemberController.java
  src/main/java/com/dnd/gongmuin/member/dto/request/LogoutRequest.java
  src/main/java/com/dnd/gongmuin/member/dto/request/ReissueRequest.java
  src/main/java/com/dnd/gongmuin/member/dto/response/LogoutResponse.java
  src/main/java/com/dnd/gongmuin/member/dto/response/ReissueResponse.java
  src/main/java/com/dnd/gongmuin/member/exception/MemberErrorCode.java
  src/main/java/com/dnd/gongmuin/member/service/MemberService.java
  src/main/java/com/dnd/gongmuin/security/handler/CustomOauth2SuccessHandler.java
  src/main/java/com/dnd/gongmuin/security/jwt/util/TokenAuthenticationFilter.java
  src/main/java/com/dnd/gongmuin/security/jwt/util/TokenProvider.java
  src/main/java/com/dnd/gongmuin/security/service/TokenService.java
  src/test/java/com/dnd/gongmuin/auth/domain/ProviderTest.java
  src/test/java/com/dnd/gongmuin/common/fixture/MemberFixture.java
  src/test/java/com/dnd/gongmuin/common/support/ApiTestSupport.java
  src/test/java/com/dnd/gongmuin/mail/service/MailServiceTest.java
  src/test/java/com/dnd/gongmuin/member/controller/MemberControllerTest.java
  src/test/java/com/dnd/gongmuin/member/service/MemberServiceTest.java
  src/test/java/com/dnd/gongmuin/security/jwt/TokenProviderTest.java
Labels: ✨ feat

#30 [Feat #29] API 누락 Swagger 작성 및 임시 토큰 발급 API
  src/main/java/com/dnd/gongmuin/auth/cotroller/AuthController.java
  src/main/java/com/dnd/gongmuin/auth/dto/LoginRequest.java
  src/main/java/com/dnd/gongmuin/auth/service/AuthService.java
  src/main/java/com/dnd/gongmuin/mail/controller/MailController.java
  src/main/java/com/dnd/gongmuin/member/controller/MemberController.java
  src/main/java/com/dnd/gongmuin/member/dto/request/AdditionalInfoRequest.java
  src/main/java/com/dnd/gongmuin/member/dto/request/LogoutRequest.java
  src/main/java/com/dnd/gongmuin/member/dto/request/ReissueRequest.java
  src/main/java/com/dnd/gongmuin/member/dto/request/ValidateNickNameRequest.java
  src/main/java/com/dnd/gongmuin/member/dto/response/LogoutResponse.java
  src/main/java/com/dnd/gongmuin/member/dto/response/ReissueResponse.java
  src/main/java/com/dnd/gongmuin/member/dto/response/SignUpResponse.java
  src/main/java/com/dnd/gongmuin/member/dto/response/ValidateNickNameResponse.java
  src/main/java/com/dnd/gongmuin/member/repository/MemberRepository.java
  src/main/java/com/dnd/gongmuin/member/service/MemberService.java
  src/main/java/com/dnd/gongmuin/security/config/SecurityConfig.java
  src/main/java/com/dnd/gongmuin/security/config/WebConfig.java
  src/test/java/com/dnd/gongmuin/member/service/MemberServiceTest.java
Labels: ✨ feat

#32 [fix #31] ec2 서버 redis 인증 문제
  .gitignore
  src/main/java/com/dnd/gongmuin/common/config/RedisConfig.java
Labels: 🚨 fix

#35 [fix #33] 시류리티 config 변경 및 API 인증 예외 처리
  src/main/java/com/dnd/gongmuin/security/config/SecurityConfig.java
  src/main/java/com/dnd/gongmuin/security/config/WebConfig.java
  src/main/java/com/dnd/gongmuin/security/exception/JwtErrorCode.java
  src/main/java/com/dnd/gongmuin/security/exception/SecurityErrorCode.java
  src/main/java/com/dnd/gongmuin/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/dnd/gongmuin/security/jwt/util/TokenExceptionFilter.java
  src/main/java/com/dnd/gongmuin/security/jwt/util/TokenProvider.java
Labels: 빠른 리뷰!

#37 [feat #36] 임시 로그인 API 인가 허용
  src/main/java/com/dnd/gongmuin/security/config/SecurityConfig.java
Labels: 🚨 fix, 빠른 리뷰!

#40 [feat #39] 사용자 프로필 조회/수정 API
  src/main/java/com/dnd/gongmuin/auth/cotroller/AuthController.java
  src/main/java/com/dnd/gongmuin/auth/dto/LoginRequest.java
  src/main/java/com/dnd/gongmuin/auth/dto/TempLoginRequest.java
  src/main/java/com/dnd/gongmuin/auth/service/AuthService.java
  src/main/java/com/dnd/gongmuin/member/controller/MemberController.java
  src/main/java/com/dnd/gongmuin/member/domain/JobCategory.java
  src/main/java/com/dnd/gongmuin/member/domain/Member.java
  src/main/java/com/dnd/gongmuin/member/dto/MemberMapper.java
  src/main/java/com/dnd/gongmuin/member/dto/request/UpdateMemberProfileRequest.java
  src/main/java/com/dnd/gongmuin/member/dto/response/MemberProfileResponse.java
  src/main/java/com/dnd/gongmuin/member/exception/MemberErrorCode.java
  src/main/java/com/dnd/gongmuin/member/repository/MemberRepository.java
  src/main/java/com/dnd/gongmuin/member/service/MemberService.java
  src/test/java/com/dnd/gongmuin/auth/controller/AuthControllerTest.java
  src/test/java/com/dnd/gongmuin/member/controller/MemberControllerTest.java
  src/test/java/com/dnd/gongmuin/member/service/MemberServiceTest.java
Labels: ✨ feat

#44 [feat #38] 질문글 상호작용 API
  src/main/java/com/dnd/gongmuin/answer/service/AnswerService.java
  src/main/java/com/dnd/gongmuin/post_interaction/controller/InteractionController.java
  src/main/java/com/dnd/gongmuin/post_interaction/domain/Interaction.java
  src/main/java/com/dnd/gongmuin/post_interaction/domain/InteractionCount.java
  src/main/java/com/dnd/gongmuin/post_interaction/domain/InteractionType.java
  src/main/java/com/dnd/gongmuin/post_interaction/domain/PostInteraction.java
  src/main/java/com/dnd/gongmuin/post_interaction/dto/InteractionMapper.java
  src/main/java/com/dnd/gongmuin/post_interaction/dto/InteractionResponse.java
  src/main/java/com/dnd/gongmuin/post_interaction/exception/InteractionErrorCode.java
  src/main/java/com/dnd/gongmuin/post_interaction/repository/InteractionCountRepository.java
  src/main/java/com/dnd/gongmuin/post_interaction/repository/InteractionRepository.java
  src/main/java/com/dnd/gongmuin/post_interaction/service/InteractionService.java
  src/main/java/com/dnd/gongmuin/question_post/domain/QuestionPost.java
  src/test/java/com/dnd/gongmuin/common/fixture/InteractionCountFixture.java
  src/test/java/com/dnd/gongmuin/common/fixture/InteractionFixture.java
  src/test/java/com/dnd/gongmuin/common/fixture/MemberFixture.java
  src/test/java/com/dnd/gongmuin/post_interaction/controller/InteractionControllerTest.java
  src/test/java/com/dnd/gongmuin/post_interaction/service/InteractionServiceTest.java
Labels: ✨ feat

#49 [refactor #48] 상호작용 API 리팩토링
  src/main/java/com/dnd/gongmuin/post_interaction/controller/InteractionController.java
  src/main/java/com/dnd/gongmuin/post_interaction/domain/Interaction.java
  src/main/java/com/dnd/gongmuin/post_interaction/domain/InteractionCount.java
  src/main/java/com/dnd/gongmuin/post_interaction/exception/InteractionErrorCode.java
  src/main/java/com/dnd/gongmuin/post_interaction/service/InteractionService.java
  src/main/java/com/dnd/gongmuin/question_post/controller/QuestionPostController.java
  src/main/java/com/dnd/gongmuin/s3/controller/S3Controller.java
  src/test/java/com/dnd/gongmuin/post_interaction/service/InteractionServiceTest.java
Labels: ♻️ refactor

#52 [feat #51] 질문 검색 결과에 북마크 수, 추천 수 추가
  src/main/java/com/dnd/gongmuin/post_interaction/controller/InteractionController.java
  src/main/java/com/dnd/gongmuin/question_post/dto/QuestionPostMapper.java
  src/main/java/com/dnd/gongmuin/question_post/dto/response/QuestionPostDetailResponse.java
  src/main/java/com/dnd/gongmuin/question_post/dto/response/QuestionPostSimpleResponse.java
  src/main/java/com/dnd/gongmuin/question_post/repository/QuestionPostQueryRepository.java
  src/main/java/com/dnd/gongmuin/question_post/repository/QuestionPostQueryRepositoryImpl.java
  src/main/java/com/dnd/gongmuin/question_post/repository/QuestionPostRepository.java
  src/main/java/com/dnd/gongmuin/question_post/service/QuestionPostService.java
  src/test/java/com/dnd/gongmuin/common/fixture/InteractionCountFixture.java
  src/test/java/com/dnd/gongmuin/common/fixture/InteractionFixture.java
  src/test/java/com/dnd/gongmuin/post_interaction/service/InteractionServiceTest.java
  src/test/java/com/dnd/gongmuin/question_post/repository/QuestionPostRepositoryTest.java
Labels: ✨ feat

#55 [feat #53] 추천 질문 조회 API
  src/main/java/com/dnd/gongmuin/question_post/controller/QuestionPostController.java
  src/main/java/com/dnd/gongmuin/question_post/dto/response/RecQuestionPostResponse.java
  src/main/java/com/dnd/gongmuin/question_post/repository/QuestionPostQueryRepository.java
  src/main/java/com/dnd/gongmuin/question_post/repository/QuestionPostQueryRepositoryImpl.java
  src/main/java/com/dnd/gongmuin/question_post/service/QuestionPostService.java
  src/test/java/com/dnd/gongmuin/common/fixture/InteractionFixture.java
  src/test/java/com/dnd/gongmuin/common/fixture/MemberFixture.java
  src/test/java/com/dnd/gongmuin/member/controller/MemberControllerTest.java
  src/test/java/com/dnd/gongmuin/member/repository/MemberRepositoryTest.java
  src/test/java/com/dnd/gongmuin/question_post/controller/QuestionPostControllerTest.java
  src/test/java/com/dnd/gongmuin/question_post/repository/QuestionPostRepositoryTest.java
Labels: ✨ feat

#58 [refactor #54] 로그인 후 JWT 발급 리팩토링
  src/main/java/com/dnd/gongmuin/auth/cotroller/AuthController.java
  src/main/java/com/dnd/gongmuin/auth/domain/Auth.java
  src/main/java/com/dnd/gongmuin/auth/dto/request/AdditionalInfoRequest.java
  src/main/java/com/dnd/gongmuin/auth/dto/request/TempLoginRequest.java
  src/main/java/com/dnd/gongmuin/auth/dto/request/ValidateNickNameRequest.java
  src/main/java/com/dnd/gongmuin/auth/dto/response/LogoutResponse.java
  src/main/java/com/dnd/gongmuin/auth/dto/response/ReissueResponse.java
  src/main/java/com/dnd/gongmuin/auth/dto/response/SignUpResponse.java
  src/main/java/com/dnd/gongmuin/auth/dto/response/ValidateNickNameResponse.java
  src/main/java/com/dnd/gongmuin/auth/service/AuthService.java
  src/main/java/com/dnd/gongmuin/common/config/SwaggerConfig.java
  src/main/java/com/dnd/gongmuin/member/dto/request/LogoutRequest.java
  src/main/java/com/dnd/gongmuin/member/dto/request/ReissueRequest.java
  src/main/java/com/dnd/gongmuin/member/dto/response/ReissueResponse.java
  src/main/java/com/dnd/gongmuin/member/service/MemberService.java
  src/main/java/com/dnd/gongmuin/security/config/SecurityConfig.java
  src/main/java/com/dnd/gongmuin/security/handler/CustomOauth2SuccessHandler.java
  src/main/java/com/dnd/gongmuin/security/jwt/util/CookieUtil.java
  src/main/java/com/dnd/gongmuin/security/jwt/util/TokenAuthenticationFilter.java
  src/main/java/com/dnd/gongmuin/security/jwt/util/TokenProvider.java
  src/test/java/com/dnd/gongmuin/answer/controller/AnswerControllerTest.java
  src/test/java/com/dnd/gongmuin/auth/controller/AuthControllerTest.java
  src/test/java/com/dnd/gongmuin/auth/service/AuthServiceTest.java
  src/test/java/com/dnd/gongmuin/common/fixture/AuthFixture.java
  src/test/java/com/dnd/gongmuin/common/support/ApiTestSupport.java
  src/test/java/com/dnd/gongmuin/mail/controller/MailControllerTest.java
  src/test/java/com/dnd/gongmuin/member/controller/MemberControllerTest.java
  src/test/java/com/dnd/gongmuin/member/domain/MemberTest.java
  src/test/java/com/dnd/gongmuin/member/service/MemberServiceTest.java
  src/test/java/com/dnd/gongmuin/post_interaction/controller/InteractionControllerTest.java
  src/test/java/com/dnd/gongmuin/question_post/controller/QuestionPostControllerTest.java
Labels: ♻️ refactor

#60 [feat #59] Security Role 도입 및 임시 로그인 API
  src/main/java/com/dnd/gongmuin/auth/controller/AuthController.java
  src/main/java/com/dnd/gongmuin/auth/dto/request/TempSignInRequest.java
  src/main/java/com/dnd/gongmuin/auth/dto/request/TempSignUpRequest.java
  src/main/java/com/dnd/gongmuin/auth/service/AuthService.java
  src/main/java/com/dnd/gongmuin/member/domain/Member.java
  src/main/java/com/dnd/gongmuin/member/service/MemberService.java
  src/main/java/com/dnd/gongmuin/security/config/SecurityConfig.java
  src/main/java/com/dnd/gongmuin/security/exception/SecurityErrorCode.java
  src/main/java/com/dnd/gongmuin/security/handler/CustomAccessDeniedHandler.java
  src/main/java/com/dnd/gongmuin/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/dnd/gongmuin/security/handler/CustomOauth2SuccessHandler.java
  src/main/java/com/dnd/gongmuin/security/jwt/util/TokenExceptionFilter.java
  src/main/java/com/dnd/gongmuin/security/oauth2/AuthInfo.java
  src/main/java/com/dnd/gongmuin/security/oauth2/CustomOauth2User.java
  src/main/java/com/dnd/gongmuin/security/service/CustomOauth2UserService.java
  src/test/java/com/dnd/gongmuin/auth/controller/AuthControllerTest.java
  src/test/java/com/dnd/gongmuin/auth/service/AuthServiceTest.java
  src/test/java/com/dnd/gongmuin/common/fixture/MemberFixture.java
  src/test/java/com/dnd/gongmuin/common/support/ApiTestSupport.java
  src/test/java/com/dnd/gongmuin/member/repository/MemberRepositoryTest.java
  src/test/java/com/dnd/gongmuin/security/jwt/TokenProviderTest.java
Labels: ✨ feat

#62 [feat #61] String-> Enum 변환 실패 시 커스텀 예외 반환
  src/main/java/com/dnd/gongmuin/answer/controller/AnswerController.java
  src/main/java/com/dnd/gongmuin/member/domain/JobCategory.java
  src/main/java/com/dnd/gongmuin/member/domain/JobGroup.java
  src/main/java/com/dnd/gongmuin/member/exception/MemberErrorCode.java
  src/main/java/com/dnd/gongmuin/post_interaction/domain/InteractionType.java
  src/main/java/com/dnd/gongmuin/post_interaction/exception/InteractionErrorCode.java
  src/main/java/com/dnd/gongmuin/question_post/controller/QuestionPostController.java
  src/main/java/com/dnd/gongmuin/s3/exception/S3ErrorCode.java
Labels: ✨ feat

#64 [chore #63] Jacoco 세팅하기
  .github/workflows/ci.yml
  build.gradle
  lombok.config
Labels: ⚙️ chore

#66 [refactor #65] 소셜로그인 완료 후 리다이렉션 변경
  src/main/java/com/dnd/gongmuin/security/handler/CustomOauth2SuccessHandler.java
Labels: 빠른 리뷰!, ♻️ refactor, ⚙️ chore

#70 [fix #69] 프론트 요청 시 쿠키 값을 읽지 못하는 issue 해결
  src/main/java/com/dnd/gongmuin/security/config/WebConfig.java
  src/main/java/com/dnd/gongmuin/security/jwt/util/CookieUtil.java
Labels: 🚨 fix, 빠른 리뷰!

#68 [feat #67] Member에 프로필 이미지 번호 필드 추가
  src/main/java/com/dnd/gongmuin/answer/dto/AnswerMapper.java
  src/main/java/com/dnd/gongmuin/member/domain/Member.java
  src/main/java/com/dnd/gongmuin/question_post/dto/QuestionPostMapper.java
  src/main/java/com/dnd/gongmuin/question_post/dto/response/MemberInfo.java
  src/test/java/com/dnd/gongmuin/question_post/controller/QuestionPostControllerTest.java
Labels: ✨ feat

#73 [fix #69] 토큰 CORS 해결
  src/main/java/com/dnd/gongmuin/security/config/SecurityConfig.java
  src/main/java/com/dnd/gongmuin/security/config/WebConfig.java
Labels: 🚨 fix, 빠른 리뷰!

#72 [feat #71] 질문 상세 조회에 상호작용 여부 필드 추가
  src/main/java/com/dnd/gongmuin/member/domain/Member.java
  src/main/java/com/dnd/gongmuin/post_interaction/repository/InteractionRepository.java
  src/main/java/com/dnd/gongmuin/question_post/controller/QuestionPostController.java
  src/main/java/com/dnd/gongmuin/question_post/dto/QuestionPostMapper.java
  src/main/java/com/dnd/gongmuin/question_post/dto/response/QuestionPostDetailResponse.java
  src/main/java/com/dnd/gongmuin/question_post/service/QuestionPostService.java
  src/test/java/com/dnd/gongmuin/question_post/controller/QuestionPostControllerTest.java
  src/test/java/com/dnd/gongmuin/question_post/service/QuestionPostServiceTest.java
Labels: ✨ feat

#76 [fix #75, #77] : 잘못된 인가 허용처리 수정, 마이페이지 게시글 목록 조회 응답 DTO 필드 네이밍 변경
  src/main/java/com/dnd/gongmuin/member/dto/response/AnsweredQuestionPostsByMemberResponse.java
  src/main/java/com/dnd/gongmuin/member/dto/response/BookmarksByMemberResponse.java
  src/main/java/com/dnd/gongmuin/member/dto/response/QuestionPostsByMemberResponse.java
  src/main/java/com/dnd/gongmuin/member/repository/MemberCustomImpl.java
  src/main/java/com/dnd/gongmuin/security/config/SecurityConfig.java
  src/test/java/com/dnd/gongmuin/member/repository/MemberRepositoryTest.java
Labels: 🚨 fix

#79 [feat #43] 마이페이지 크레딧 내역 조회 API
  src/main/java/com/dnd/gongmuin/credit_history/domain/CreditHistory.java
  src/main/java/com/dnd/gongmuin/credit_history/domain/CreditType.java
  src/main/java/com/dnd/gongmuin/credit_history/dto/CreditHistoryMapper.java
  src/main/java/com/dnd/gongmuin/credit_history/repository/CreditHistoryRepository.java
  src/main/java/com/dnd/gongmuin/credit_history/service/CreditHistoryService.java
  src/main/java/com/dnd/gongmuin/member/controller/MemberController.java
  src/main/java/com/dnd/gongmuin/member/domain/Member.java
  src/main/java/com/dnd/gongmuin/member/dto/response/AnsweredQuestionPostsResponse.java
  src/main/java/com/dnd/gongmuin/member/dto/response/BookmarksResponse.java
  src/main/java/com/dnd/gongmuin/member/dto/response/CreditHistoryResponse.java
  src/main/java/com/dnd/gongmuin/member/dto/response/QuestionPostsResponse.java
  src/main/java/com/dnd/gongmuin/member/repository/MemberCustom.java
  src/main/java/com/dnd/gongmuin/member/repository/MemberCustomImpl.java
  src/main/java/com/dnd/gongmuin/member/service/MemberService.java
  src/test/java/com/dnd/gongmuin/credit_history/fixture/CreditHistoryFixture.java
  src/test/java/com/dnd/gongmuin/credit_history/service/CreditHistoryServiceTest.java
  src/test/java/com/dnd/gongmuin/member/controller/MemberControllerTest.java
  src/test/java/com/dnd/gongmuin/member/repository/MemberRepositoryTest.java
Labels: ✨ feat

#81 [feat #80] 프로필 조회 응답 DTO 필드 추가
  src/main/java/com/dnd/gongmuin/member/domain/Member.java
  src/main/java/com/dnd/gongmuin/member/dto/MemberMapper.java
  src/main/java/com/dnd/gongmuin/member/dto/response/MemberProfileResponse.java
  src/test/java/com/dnd/gongmuin/member/controller/MemberControllerTest.java
  src/test/java/com/dnd/gongmuin/member/service/MemberServiceTest.java
Labels: ✨ feat

#83 [feat #82] 유저 정보 API
  src/main/java/com/dnd/gongmuin/member/controller/MemberController.java
  src/main/java/com/dnd/gongmuin/member/dto/MemberMapper.java
  src/main/java/com/dnd/gongmuin/member/dto/response/MemberInformationResponse.java
  src/main/java/com/dnd/gongmuin/member/service/MemberService.java
  src/test/java/com/dnd/gongmuin/member/controller/MemberControllerTest.java
  src/test/java/com/dnd/gongmuin/member/service/MemberServiceTest.java
Labels: ✨ feat

#85 [refactor #84] JWT 토큰 만료시간 변경
  src/main/java/com/dnd/gongmuin/security/jwt/util/TokenProvider.java
  src/test/java/com/dnd/gongmuin/security/jwt/TokenProviderTest.java
Labels: 빠른 리뷰!, ♻️ refactor

#87 [refactor #86] 상호작용 비즈니스 로직 리팩토링
  src/main/java/com/dnd/gongmuin/post_interaction/domain/InteractionCount.java
  src/main/java/com/dnd/gongmuin/post_interaction/dto/InteractionMapper.java
  src/main/java/com/dnd/gongmuin/post_interaction/exception/InteractionErrorCode.java
  src/main/java/com/dnd/gongmuin/post_interaction/service/InteractionService.java
  src/test/java/com/dnd/gongmuin/post_interaction/service/InteractionServiceTest.java
Labels: ♻️ refactor

#89 [fix #88] security-jwt hotfix
  src/main/java/com/dnd/gongmuin/auth/controller/AuthController.java
  src/main/java/com/dnd/gongmuin/auth/dto/response/TempSignResponse.java
  src/main/java/com/dnd/gongmuin/auth/service/AuthService.java
  src/main/java/com/dnd/gongmuin/credit_history/domain/CreditType.java
  src/main/java/com/dnd/gongmuin/member/domain/Member.java
  src/main/java/com/dnd/gongmuin/security/jwt/util/CookieUtil.java
Labels: 🚨 fix

#93 [feat #92] 채팅방 메시지 조회 API
  build.gradle
  docker-compose.yml
  src/main/java/com/dnd/gongmuin/chat/controller/ChatRoomController.java
  src/main/java/com/dnd/gongmuin/chat/domain/ChatMessage.java
  src/main/java/com/dnd/gongmuin/chat/domain/MessageType.java
  src/main/java/com/dnd/gongmuin/chat/dto/ChatMapper.java
  src/main/java/com/dnd/gongmuin/chat/dto/ChatMessageRequest.java
  src/main/java/com/dnd/gongmuin/chat/dto/ChatMessageResponse.java
  src/main/java/com/dnd/gongmuin/chat/exception/ChatErrorCode.java
  src/main/java/com/dnd/gongmuin/chat/repository/ChatMessageRepository.java
  src/main/java/com/dnd/gongmuin/chat/service/ChatRoomService.java
  src/test/java/com/dnd/gongmuin/chat/controller/ChatRoomControllerTest.java
  src/test/java/com/dnd/gongmuin/chat/service/ChatRoomServiceTest.java
  src/test/java/com/dnd/gongmuin/common/fixture/ChatMessageFixture.java
  src/test/java/com/dnd/gongmuin/common/support/TestContainerSupport.java
Labels: ✨ feat, ⚙️ chore

#94 [refactor #90] repository 어노테이션 명시
  src/main/java/com/dnd/gongmuin/answer/repository/AnswerRepository.java
  src/main/java/com/dnd/gongmuin/auth/repository/AuthRepository.java
  src/main/java/com/dnd/gongmuin/credit_history/repository/CreditHistoryRepository.java
  src/main/java/com/dnd/gongmuin/member/repository/MemberRepository.java
  src/main/java/com/dnd/gongmuin/post_interaction/controller/InteractionController.java
  src/main/java/com/dnd/gongmuin/post_interaction/repository/InteractionCountRepository.java
  src/main/java/com/dnd/gongmuin/post_interaction/repository/InteractionRepository.java
  src/main/java/com/dnd/gongmuin/question_post/repository/QuestionPostImageRepository.java
  src/main/java/com/dnd/gongmuin/question_post/repository/QuestionPostRepository.java
Labels: ♻️ refactor
