Repository dnd-side-project/dnd-11th-3-backend, pull requests merged in 2024-12, with the labels that each got.

#165 [fix #163] 추가 정보 기입 시 닉네임 2차 검증 누락 해결
  src/main/java/com/dnd/gongmuin/auth/service/AuthService.java
  src/main/java/com/dnd/gongmuin/member/exception/MemberErrorCode.java
  src/test/java/com/dnd/gongmuin/auth/service/AuthServiceTest.java
Labels: 🚨 fix

#166 [feat #164] 채팅 요청 상세 조회 API 응답값 추가
  src/main/java/com/dnd/gongmuin/chat_inquiry/dto/ChatInquiryDetailResponse.java
  src/main/java/com/dnd/gongmuin/chat_inquiry/dto/ChatInquiryMapper.java
  src/main/java/com/dnd/gongmuin/chat_inquiry/dto/CreateChatInquiryResponse.java
  src/main/java/com/dnd/gongmuin/chat_inquiry/service/ChatInquiryService.java
  src/test/java/com/dnd/gongmuin/chat_inquiry/controller/ChatInquiryControllerTest.java
Labels: ✨ feat

#170 [fix] 크레딧 입금/출금 내역조회 오류 해결
  src/main/java/com/dnd/gongmuin/credit_history/domain/CreditType.java
Labels: 🚨 fix, 빠른 리뷰!

#168 [feat #167] 질문 게시글 작성 로직 변경
  src/main/java/com/dnd/gongmuin/answer/exception/AnswerErrorCode.java
  src/main/java/com/dnd/gongmuin/answer/service/AnswerService.java
  src/main/java/com/dnd/gongmuin/credit_history/domain/CreditType.java
  src/main/java/com/dnd/gongmuin/credit_history/service/CreditHistoryService.java
  src/main/java/com/dnd/gongmuin/question_post/domain/QuestionPost.java
  src/main/java/com/dnd/gongmuin/question_post/domain/QuestionPostStatus.java
  src/main/java/com/dnd/gongmuin/question_post/dto/QuestionPostMapper.java
  src/main/java/com/dnd/gongmuin/question_post/dto/RefundQuestionPostDto.java
  src/main/java/com/dnd/gongmuin/question_post/dto/response/QuestionPostDetailResponse.java
  src/main/java/com/dnd/gongmuin/question_post/dto/response/RegisterQuestionPostResponse.java
  src/main/java/com/dnd/gongmuin/question_post/exception/QuestionPostErrorCode.java
  src/main/java/com/dnd/gongmuin/question_post/repository/QuestionPostQueryRepository.java
  src/main/java/com/dnd/gongmuin/question_post/repository/QuestionPostQueryRepositoryImpl.java
  src/main/java/com/dnd/gongmuin/question_post/scheduler/QuestionPostScheduler.java
  src/main/java/com/dnd/gongmuin/question_post/service/QuestionPostService.java
  src/test/java/com/dnd/gongmuin/answer/service/AnswerServiceTest.java
  src/test/java/com/dnd/gongmuin/auth/controller/AuthControllerTest.java
  src/test/java/com/dnd/gongmuin/credit_history/service/CreditHistoryServiceTest.java
  src/test/java/com/dnd/gongmuin/member/controller/MemberControllerTest.java
  src/test/java/com/dnd/gongmuin/member/repository/MemberRepositoryTest.java
  src/test/java/com/dnd/gongmuin/question_post/controller/QuestionPostControllerTest.java
  src/test/java/com/dnd/gongmuin/question_post/repository/QuestionPostRepositoryTest.java
  src/test/java/com/dnd/gongmuin/question_post/service/QuestionPostServiceTest.java
Labels: 🚨 fix, ✨ feat, ♻️ refactor

#172 [fix #171] status enum 타입 String으로 변경
  src/main/java/com/dnd/gongmuin/answer/service/AnswerService.java
  src/main/java/com/dnd/gongmuin/question_post/domain/QuestionPost.java
  src/main/java/com/dnd/gongmuin/question_post/domain/QuestionPostStatus.java
  src/main/java/com/dnd/gongmuin/question_post/dto/QuestionPostMapper.java
  src/main/java/com/dnd/gongmuin/question_post/repository/QuestionPostQueryRepositoryImpl.java
  src/test/java/com/dnd/gongmuin/answer/service/AnswerServiceTest.java
  src/test/java/com/dnd/gongmuin/question_post/repository/QuestionPostRepositoryTest.java
Labels: 🚨 fix

#176 [refactor #175] 크레딧 저장 내역 함수 통합
  src/main/java/com/dnd/gongmuin/answer/service/AnswerService.java
  src/main/java/com/dnd/gongmuin/chat_inquiry/service/ChatInquiryService.java
  src/main/java/com/dnd/gongmuin/common/config/SwaggerConfig.java
  src/main/java/com/dnd/gongmuin/credit_history/service/CreditHistoryService.java
  src/main/java/com/dnd/gongmuin/question_post/service/QuestionPostService.java
  src/test/java/com/dnd/gongmuin/credit_history/service/CreditHistoryServiceTest.java
  src/test/java/com/dnd/gongmuin/question_post/service/QuestionPostServiceTest.java
Labels: ♻️ refactor
