Repository dnd-side-project/dnd-11th-3-backend, pull requests merged in 2024-09, with the labels that each got.

#96 [feat #95] 채팅 전송 웹소켓 API
  .gitignore
  build.gradle
  src/main/java/com/dnd/gongmuin/chat/controller/ChatMessageController.java
  src/main/java/com/dnd/gongmuin/chat/controller/ChatRoomController.java
  src/main/java/com/dnd/gongmuin/chat/domain/ChatMessage.java
  src/main/java/com/dnd/gongmuin/chat/dto/ChatMapper.java
  src/main/java/com/dnd/gongmuin/chat/dto/ChatMessageRequest.java
  src/main/java/com/dnd/gongmuin/chat/dto/ChatMessageResponse.java
  src/main/java/com/dnd/gongmuin/chat/service/ChatMessageService.java
  src/main/java/com/dnd/gongmuin/chat/service/ChatRoomService.java
  src/main/java/com/dnd/gongmuin/common/config/WebSocketConfig.java
  src/main/java/com/dnd/gongmuin/security/config/SecurityConfig.java
  src/test/java/com/dnd/gongmuin/chat/controller/ChatRoomControllerTest.java
  src/test/java/com/dnd/gongmuin/common/fixture/ChatMessageFixture.java
Labels: ✨ feat

#97 [feat #91] 알림 목록/읽기 API
  src/main/java/com/dnd/gongmuin/answer/service/AnswerService.java
  src/main/java/com/dnd/gongmuin/member/repository/MemberCustomImpl.java
  src/main/java/com/dnd/gongmuin/notification/controller/NotificationController.java
  src/main/java/com/dnd/gongmuin/notification/domain/Notification.java
  src/main/java/com/dnd/gongmuin/notification/domain/NotificationType.java
  src/main/java/com/dnd/gongmuin/notification/dto/NotificationMapper.java
  src/main/java/com/dnd/gongmuin/notification/dto/request/readNotificationRequest.java
  src/main/java/com/dnd/gongmuin/notification/dto/response/NotificationsResponse.java
  src/main/java/com/dnd/gongmuin/notification/dto/response/readNotificationResponse.java
  src/main/java/com/dnd/gongmuin/notification/exception/NotificationErrorCode.java
  src/main/java/com/dnd/gongmuin/notification/repository/NotificationCustom.java
  src/main/java/com/dnd/gongmuin/notification/repository/NotificationCustomImpl.java
  src/main/java/com/dnd/gongmuin/notification/repository/NotificationRepository.java
  src/main/java/com/dnd/gongmuin/notification/service/NotificationService.java
  src/test/java/com/dnd/gongmuin/answer/service/AnswerServiceTest.java
  src/test/java/com/dnd/gongmuin/common/fixture/NotificationFixture.java
  src/test/java/com/dnd/gongmuin/notification/controller/NotificationControllerTest.java
  src/test/java/com/dnd/gongmuin/notification/repository/NotificationRepositoryTest.java
  src/test/java/com/dnd/gongmuin/notification/service/NotificationServiceTest.java
Labels: ✨ feat

#100 [fix #99] CORS 중복 Bean 제거
  src/main/java/com/dnd/gongmuin/security/config/WebConfig.java
Labels: 🚨 fix

#102 [refactor #100] oauth kakao login refactor
  src/main/java/com/dnd/gongmuin/auth/domain/Auth.java
  src/main/java/com/dnd/gongmuin/auth/domain/AuthStatus.java
  src/main/java/com/dnd/gongmuin/auth/repository/AuthRepository.java
  src/main/java/com/dnd/gongmuin/auth/service/AuthService.java
  src/main/java/com/dnd/gongmuin/member/domain/Provider.java
  src/main/java/com/dnd/gongmuin/member/service/MemberService.java
  src/main/java/com/dnd/gongmuin/security/handler/CustomAccessDeniedHandler.java
  src/main/java/com/dnd/gongmuin/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/dnd/gongmuin/security/handler/CustomOauth2FailureHandler.java
  src/main/java/com/dnd/gongmuin/security/handler/CustomOauth2SuccessHandler.java
  src/main/java/com/dnd/gongmuin/security/oauth2/KakaoResponse.java
  src/main/java/com/dnd/gongmuin/security/service/CustomOauth2UserService.java
  src/test/java/com/dnd/gongmuin/auth/domain/ProviderTest.java
  src/test/java/com/dnd/gongmuin/auth/service/AuthServiceTest.java
  src/test/java/com/dnd/gongmuin/common/fixture/AuthFixture.java
  src/test/java/com/dnd/gongmuin/member/service/MemberServiceTest.java
Labels: ♻️ refactor

#105 [refactor #104] 알림 생성 API Refactor
  src/main/java/com/dnd/gongmuin/answer/service/AnswerService.java
  src/main/java/com/dnd/gongmuin/notification/controller/NotificationController.java
  src/main/java/com/dnd/gongmuin/notification/dto/NotificationEvent.java
  src/main/java/com/dnd/gongmuin/notification/dto/response/NotificationResponse.java
  src/main/java/com/dnd/gongmuin/notification/repository/NotificationCustom.java
  src/main/java/com/dnd/gongmuin/notification/repository/NotificationCustomImpl.java
  src/main/java/com/dnd/gongmuin/notification/service/NotificationService.java
  src/test/java/com/dnd/gongmuin/answer/service/AnswerServiceTest.java
  src/test/java/com/dnd/gongmuin/notification/repository/NotificationRepositoryTest.java
  src/test/java/com/dnd/gongmuin/notification/service/NotificationServiceTest.java
Labels: ♻️ refactor

#107 [feat #98] 채팅방 생성 API
  src/main/java/com/dnd/gongmuin/chat/controller/ChatMessageController.java
  src/main/java/com/dnd/gongmuin/chat/controller/ChatRoomController.java
  src/main/java/com/dnd/gongmuin/chat/domain/ChatRoom.java
  src/main/java/com/dnd/gongmuin/chat/dto/ChatMessageMapper.java
  src/main/java/com/dnd/gongmuin/chat/dto/ChatMessageResponse.java
  src/main/java/com/dnd/gongmuin/chat/dto/ChatRoomMapper.java
  src/main/java/com/dnd/gongmuin/chat/dto/request/ChatMessageRequest.java
  src/main/java/com/dnd/gongmuin/chat/dto/request/CreateChatRoomRequest.java
  src/main/java/com/dnd/gongmuin/chat/dto/response/ChatMessageResponse.java
  src/main/java/com/dnd/gongmuin/chat/dto/response/ChatRoomDetailResponse.java
  src/main/java/com/dnd/gongmuin/chat/exception/ChatErrorCode.java
  src/main/java/com/dnd/gongmuin/chat/repository/ChatRoomRepository.java
  src/main/java/com/dnd/gongmuin/chat/service/ChatMessageService.java
  src/main/java/com/dnd/gongmuin/chat/service/ChatRoomService.java
  src/main/java/com/dnd/gongmuin/common/config/MongoConfig.java
  src/main/java/com/dnd/gongmuin/converter/DateToLocalDateTimeKstConverter.java
  src/main/java/com/dnd/gongmuin/converter/LocalDateTimeToDateKstConverter.java
  src/test/java/com/dnd/gongmuin/chat/controller/ChatRoomControllerTest.java
  src/test/java/com/dnd/gongmuin/chat/service/ChatRoomServiceTest.java
  src/test/java/com/dnd/gongmuin/common/fixture/ChatRoomFixture.java
Labels: ✨ feat

#106 [feat #103] 크레딧내역 조회 프로필 번호, 시간 추가
  src/main/java/com/dnd/gongmuin/member/dto/response/CreditHistoryResponse.java
  src/main/java/com/dnd/gongmuin/member/repository/MemberCustomImpl.java
  src/test/java/com/dnd/gongmuin/common/fixture/CreditHistoryFixture.java
  src/test/java/com/dnd/gongmuin/credit_history/service/CreditHistoryServiceTest.java
  src/test/java/com/dnd/gongmuin/member/controller/MemberControllerTest.java
  src/test/java/com/dnd/gongmuin/member/repository/MemberRepositoryTest.java
Labels: ✨ feat, ♻️ refactor

#111 [feat #110] AOP Logging
  src/main/java/com/dnd/gongmuin/common/config/LoggingAspect.java
  src/main/java/com/dnd/gongmuin/member/domain/Member.java
  src/main/java/com/dnd/gongmuin/security/jwt/util/TokenAuthenticationFilter.java
  src/main/java/com/dnd/gongmuin/security/jwt/util/TokenProvider.java
Labels: ✨ feat

#109 [feat #108] 채팅 수락/거절 API
  src/main/java/com/dnd/gongmuin/chat/controller/ChatRoomController.java
  src/main/java/com/dnd/gongmuin/chat/domain/ChatRoom.java
  src/main/java/com/dnd/gongmuin/chat/domain/ChatStatus.java
  src/main/java/com/dnd/gongmuin/chat/dto/ChatRoomMapper.java
  src/main/java/com/dnd/gongmuin/chat/dto/response/AcceptChatResponse.java
  src/main/java/com/dnd/gongmuin/chat/dto/response/ChatRoomDetailResponse.java
  src/main/java/com/dnd/gongmuin/chat/dto/response/RejectChatResponse.java
  src/main/java/com/dnd/gongmuin/chat/exception/ChatErrorCode.java
  src/main/java/com/dnd/gongmuin/chat/service/ChatRoomService.java
  src/test/java/com/dnd/gongmuin/chat/controller/ChatRoomControllerTest.java
  src/test/java/com/dnd/gongmuin/chat/service/ChatRoomServiceTest.java
Labels: ✨ feat

#120 [feat #119] 채팅방 상세조회 API
  src/main/java/com/dnd/gongmuin/chat/controller/ChatRoomController.java
  src/main/java/com/dnd/gongmuin/chat/dto/ChatRoomMapper.java
  src/main/java/com/dnd/gongmuin/chat/dto/response/ChatRoomDetailResponse.java
  src/main/java/com/dnd/gongmuin/chat/exception/ChatErrorCode.java
  src/main/java/com/dnd/gongmuin/chat/service/ChatRoomService.java
  src/test/java/com/dnd/gongmuin/chat/controller/ChatRoomControllerTest.java
  src/test/java/com/dnd/gongmuin/chat/service/ChatRoomServiceTest.java
Labels: ✨ feat

#121 [feat #116] 채팅방 목록 조회 API
  src/main/java/com/dnd/gongmuin/chat/controller/ChatRoomController.java
  src/main/java/com/dnd/gongmuin/chat/dto/ChatMessageMapper.java
  src/main/java/com/dnd/gongmuin/chat/dto/request/ChatMessageRequest.java
  src/main/java/com/dnd/gongmuin/chat/dto/request/CreateChatRoomRequest.java
  src/main/java/com/dnd/gongmuin/chat/dto/response/ChatMessageResponse.java
  src/main/java/com/dnd/gongmuin/chat/dto/response/ChatRoomInfo.java
  src/main/java/com/dnd/gongmuin/chat/dto/response/ChatRoomSimpleResponse.java
  src/main/java/com/dnd/gongmuin/chat/dto/response/LatestChatMessage.java
  src/main/java/com/dnd/gongmuin/chat/repository/ChatMessageQueryRepository.java
  src/main/java/com/dnd/gongmuin/chat/repository/ChatRoomQueryRepository.java
  src/main/java/com/dnd/gongmuin/chat/repository/ChatRoomQueryRepositoryImpl.java
  src/main/java/com/dnd/gongmuin/chat/repository/ChatRoomRepository.java
  src/main/java/com/dnd/gongmuin/chat/service/ChatMessageService.java
  src/main/java/com/dnd/gongmuin/chat/service/ChatRoomService.java
  src/main/java/com/dnd/gongmuin/member/domain/Member.java
  src/test/java/com/dnd/gongmuin/chat/controller/ChatRoomControllerTest.java
  src/test/java/com/dnd/gongmuin/chat/repository/ChatMessageQueryRepositoryTest.java
  src/test/java/com/dnd/gongmuin/chat/repository/ChatRoomRepositoryTest.java
  src/test/java/com/dnd/gongmuin/common/fixture/ChatMessageFixture.java
  src/test/java/com/dnd/gongmuin/common/fixture/MemberFixture.java
Labels: ✨ feat

#124 [feat #115] 채팅 신청/수락/거절 알림 API
  src/main/java/com/dnd/gongmuin/chat/service/ChatRoomService.java
  src/main/java/com/dnd/gongmuin/notification/domain/NotificationType.java
  src/test/java/com/dnd/gongmuin/chat/service/ChatRoomServiceTest.java
Labels: ✨ feat

#123 [feat #122] 채팅방 목록 조회 API 필터링 추가
  src/main/java/com/dnd/gongmuin/chat/controller/ChatRoomController.java
  src/main/java/com/dnd/gongmuin/chat/domain/ChatStatus.java
  src/main/java/com/dnd/gongmuin/chat/exception/ChatErrorCode.java
  src/main/java/com/dnd/gongmuin/chat/repository/ChatRoomQueryRepository.java
  src/main/java/com/dnd/gongmuin/chat/repository/ChatRoomQueryRepositoryImpl.java
  src/main/java/com/dnd/gongmuin/chat/service/ChatRoomService.java
  src/test/java/com/dnd/gongmuin/chat/controller/ChatRoomControllerTest.java
  src/test/java/com/dnd/gongmuin/chat/repository/ChatRoomRepositoryTest.java
  src/test/java/com/dnd/gongmuin/post_interaction/controller/InteractionControllerTest.java
Labels: ✨ feat

#126 [feat #125] Aop logging
  src/main/java/com/dnd/gongmuin/member/dto/response/AnsweredQuestionPostsResponse.java
  src/main/java/com/dnd/gongmuin/member/dto/response/BookmarksResponse.java
  src/main/java/com/dnd/gongmuin/member/dto/response/CreditHistoryResponse.java
  src/main/java/com/dnd/gongmuin/member/dto/response/QuestionPostsResponse.java
  src/main/java/com/dnd/gongmuin/question_post/dto/response/QuestionPostSimpleResponse.java
Labels: ✨ feat
