Repository dnd-side-project/dnd-11th-3-backend, pull requests merged in 2025-02, with the labels that each got.

#199 [fix #198] Swagger CORS 오류 해결
  src/main/java/com/dnd/gongmuin/common/config/SwaggerConfig.java
Labels: 🚨 fix

#201 [chore #200] README.md 작성
  README.md
Labels: ⚙️ chore

#202 [feat #178] 질문글 작성 전 최소한의 크레딧을 보유하는지 검증한다.
  src/main/java/com/dnd/gongmuin/member/domain/Member.java
  src/main/java/com/dnd/gongmuin/question_post/controller/QuestionPostController.java
  src/main/java/com/dnd/gongmuin/question_post/dto/response/CheckQuestionPostCreditResponse.java
  src/main/java/com/dnd/gongmuin/question_post/service/QuestionPostService.java
  src/test/java/com/dnd/gongmuin/question_post/controller/QuestionPostControllerTest.java
  src/test/java/com/dnd/gongmuin/question_post/service/QuestionPostServiceTest.java
Labels: ✨ feat

#208 [feat #207] 만료된 JWT 에러 응답 추가
  src/main/java/com/dnd/gongmuin/security/exception/JwtErrorCode.java
  src/main/java/com/dnd/gongmuin/security/jwt/util/TokenProvider.java
  src/test/java/com/dnd/gongmuin/security/jwt/TokenProviderTest.java
Labels: ✨ feat

#209 [feat #203] 프론트 환경에 따른 JWT 쿠키 설정 자동 변경
  src/main/java/com/dnd/gongmuin/security/jwt/util/CookieConfig.java
  src/main/java/com/dnd/gongmuin/security/jwt/util/CookieUtil.java
  src/main/java/com/dnd/gongmuin/security/jwt/util/DevCookie.java
  src/main/java/com/dnd/gongmuin/security/jwt/util/LocalCookie.java
  src/main/java/com/dnd/gongmuin/security/jwt/util/ProdCookie.java
Labels: ✨ feat, ⚙️ chore

#211 [fix #210] 서버 설정에 따른 JWT 인증/인가 실패 해결
  src/main/java/com/dnd/gongmuin/auth/controller/AuthController.java
  src/main/java/com/dnd/gongmuin/auth/service/AuthService.java
  src/main/java/com/dnd/gongmuin/security/config/SecurityConfig.java
  src/main/java/com/dnd/gongmuin/security/handler/CustomAccessDeniedHandler.java
  src/main/java/com/dnd/gongmuin/security/jwt/util/CookieUtil.java
  src/main/java/com/dnd/gongmuin/security/jwt/util/LocalCookie.java
  src/main/java/com/dnd/gongmuin/security/jwt/util/TokenAuthenticationFilter.java
  src/main/java/com/dnd/gongmuin/security/jwt/util/TokenProvider.java
  src/test/java/com/dnd/gongmuin/auth/service/AuthServiceTest.java
  src/test/java/com/dnd/gongmuin/security/jwt/TokenProviderTest.java
Labels: 🚨 fix

#213 [fix #212] JWT 재발급 API 오류 해결
  src/main/java/com/dnd/gongmuin/auth/exception/AuthErrorCode.java
  src/main/java/com/dnd/gongmuin/auth/service/AuthService.java
  src/main/java/com/dnd/gongmuin/security/jwt/util/TokenAuthenticationFilter.java
  src/main/java/com/dnd/gongmuin/security/jwt/util/TokenProvider.java
  src/test/java/com/dnd/gongmuin/auth/service/AuthServiceTest.java
Labels: 🚨 fix, ✨ feat, ♻️ refactor, ⚙️ chore

#215 [feat #214] 쿠키 설정 변경
  src/main/java/com/dnd/gongmuin/security/jwt/util/CookieConfig.java
  src/main/java/com/dnd/gongmuin/security/jwt/util/CookieUtil.java
  src/main/java/com/dnd/gongmuin/security/jwt/util/DevCookie.java
  src/main/java/com/dnd/gongmuin/security/jwt/util/LocalCookie.java
  src/main/java/com/dnd/gongmuin/security/jwt/util/ProdCookie.java
Labels: ✨ feat, ♻️ refactor, ⚙️ chore

#217 [feat #216] 질문 검색 API에 상호작용 필드 추가
  src/main/java/com/dnd/gongmuin/question_post/controller/QuestionPostController.java
  src/main/java/com/dnd/gongmuin/question_post/dto/response/QuestionPostSimpleResponse.java
  src/main/java/com/dnd/gongmuin/question_post/repository/QuestionPostQueryRepositoryImpl.java
  src/main/java/com/dnd/gongmuin/question_post/service/QuestionPostService.java
  src/test/java/com/dnd/gongmuin/question_post/repository/QuestionPostRepositoryTest.java
Labels: ✨ feat

#218 [fix #206] 검색 결과 응답 필드에 boolean 변수 중복 생성 문제 해결
  src/main/java/com/dnd/gongmuin/chat_inquiry/controller/ChatInquiryController.java
  src/main/java/com/dnd/gongmuin/chatroom/controller/ChatRoomController.java
  src/main/java/com/dnd/gongmuin/question_post/dto/response/QuestionPostSimpleResponse.java
Labels: 🚨 fix
