Repository dnd-side-project/dnd-11th-3-backend, pull requests merged in 2025-01, with the labels that each got.

#183 [fix #182] CORS 오류 해결
  src/main/java/com/dnd/gongmuin/security/config/SecurityConfig.java
Labels: 🚨 fix, 빠른 리뷰!

#180 [feat #177] 질문 글 작성 응답 DTO 잔여 크레딧 추가
  src/main/java/com/dnd/gongmuin/question_post/dto/QuestionPostMapper.java
  src/main/java/com/dnd/gongmuin/question_post/dto/response/RegisterQuestionPostResponse.java
  src/main/java/com/dnd/gongmuin/question_post/service/QuestionPostService.java
  src/test/java/com/dnd/gongmuin/question_post/controller/QuestionPostControllerTest.java
  src/test/java/com/dnd/gongmuin/question_post/service/QuestionPostServiceTest.java
Labels: ✨ feat

#185 [fix #179] 채팅 요청 답변자 검증 로직 추가
  src/main/java/com/dnd/gongmuin/answer/repository/AnswerRepository.java
  src/main/java/com/dnd/gongmuin/chat_inquiry/exception/ChatInquiryErrorCode.java
  src/main/java/com/dnd/gongmuin/chat_inquiry/service/ChatInquiryService.java
  src/test/java/com/dnd/gongmuin/chat_inquiry/controller/ChatInquiryControllerTest.java
  src/test/java/com/dnd/gongmuin/chat_inquiry/service/ChatInquiryServiceTest.java
Labels: 🚨 fix

#187 [feat #186] 질문글 삭제 API
  src/main/java/com/dnd/gongmuin/answer/repository/AnswerRepository.java
  src/main/java/com/dnd/gongmuin/question_post/controller/QuestionPostController.java
  src/main/java/com/dnd/gongmuin/question_post/dto/response/DeleteQuestionPostResponse.java
  src/main/java/com/dnd/gongmuin/question_post/exception/QuestionPostErrorCode.java
  src/main/java/com/dnd/gongmuin/question_post/service/QuestionPostService.java
  src/test/java/com/dnd/gongmuin/question_post/controller/QuestionPostControllerTest.java
  src/test/java/com/dnd/gongmuin/question_post/service/QuestionPostServiceTest.java
Labels: ✨ feat

#189 [style #181] 답변 채택 API 네이밍 변경
  src/main/java/com/dnd/gongmuin/answer/controller/AnswerController.java
Labels: ♻️ refactor

#188 [ fix #184] 채팅 자동 거절 시 수정일 미변경 해결
  src/main/java/com/dnd/gongmuin/chat_inquiry/repository/ChatInquiryQueryRepository.java
  src/main/java/com/dnd/gongmuin/chat_inquiry/repository/ChatInquiryQueryRepositoryImpl.java
  src/main/java/com/dnd/gongmuin/chat_inquiry/scheduler/ChatInquiryScheduler.java
  src/main/java/com/dnd/gongmuin/chat_inquiry/service/ChatInquiryService.java
  src/main/java/com/dnd/gongmuin/question_post/repository/QuestionPostQueryRepository.java
  src/main/java/com/dnd/gongmuin/question_post/repository/QuestionPostQueryRepositoryImpl.java
  src/main/java/com/dnd/gongmuin/question_post/scheduler/QuestionPostScheduler.java
  src/main/java/com/dnd/gongmuin/question_post/service/QuestionPostService.java
  src/test/java/com/dnd/gongmuin/chat_inquiry/repository/ChatInquiryRepositoryTest.java
  src/test/java/com/dnd/gongmuin/chat_inquiry/service/ChatInquiryServiceTest.java
  src/test/java/com/dnd/gongmuin/question_post/repository/QuestionPostRepositoryTest.java
Labels: 🚨 fix

#194 [refactor #193] 채팅 요청 상태 업데이트 함수 수정
  src/main/java/com/dnd/gongmuin/chat_inquiry/dto/ExpiredChatInquiryDto.java
  src/main/java/com/dnd/gongmuin/chat_inquiry/repository/ChatInquiryQueryRepository.java
  src/main/java/com/dnd/gongmuin/chat_inquiry/repository/ChatInquiryQueryRepositoryImpl.java
  src/main/java/com/dnd/gongmuin/chat_inquiry/scheduler/ChatInquiryScheduler.java
  src/main/java/com/dnd/gongmuin/chat_inquiry/service/ChatInquiryService.java
  src/test/java/com/dnd/gongmuin/chat_inquiry/repository/ChatInquiryRepositoryTest.java
  src/test/java/com/dnd/gongmuin/chat_inquiry/service/ChatInquiryServiceTest.java
Labels: ♻️ refactor

#192 [fix #190] 답변자가 스스로에게 채팅 요청 보낼 수 없도록 수정
  src/main/java/com/dnd/gongmuin/chat_inquiry/exception/ChatInquiryErrorCode.java
  src/main/java/com/dnd/gongmuin/chat_inquiry/service/ChatInquiryService.java
  src/test/java/com/dnd/gongmuin/chat_inquiry/service/ChatInquiryServiceTest.java
Labels: 🚨 fix

#197 [feat #196] PathVariable 이름 추가
  src/main/java/com/dnd/gongmuin/answer/controller/AnswerController.java
Labels: ✨ feat
