Repository dnd-side-project/dnd-11th-3-backend, pull requests merged in 2025-03, with the labels that each got.

#219 [docs] S3 이미지 업로드 swagger 수정
  .github/workflows/cd_dev.yml
  src/main/java/com/dnd/gongmuin/s3/controller/S3Controller.java
Labels: 빠른 리뷰!

#224 [fix #222] S3 업로드 API 오류 해결
  src/main/java/com/dnd/gongmuin/answer/repository/AnswerRepository.java
  src/main/java/com/dnd/gongmuin/chat_inquiry/repository/ChatInquiryQueryRepositoryImpl.java
  src/main/java/com/dnd/gongmuin/chat_inquiry/service/ChatInquiryService.java
  src/main/java/com/dnd/gongmuin/question_post/controller/QuestionPostController.java
  src/main/java/com/dnd/gongmuin/s3/controller/S3Controller.java
  src/test/java/com/dnd/gongmuin/chat_inquiry/service/ChatInquiryServiceTest.java
Labels: 🚨 fix

#226 [feat #225] 질문 글 좋아요 낙관적 락을 이용한 동시성 제어
  build.gradle
  src/main/java/com/dnd/gongmuin/common/config/RetryConfig.java
  src/main/java/com/dnd/gongmuin/post_interaction/domain/InteractionCount.java
  src/main/java/com/dnd/gongmuin/post_interaction/repository/InteractionCountRepository.java
  src/main/java/com/dnd/gongmuin/post_interaction/service/InteractionService.java
  src/test/java/com/dnd/gongmuin/post_interaction/service/InteractionTransactionTest.java
Labels: ✨ feat, ♻️ refactor, ⚙️ chore

#228 [fix #227] 중복 채팅 요청 검증 로직 추가
  src/main/java/com/dnd/gongmuin/chat_inquiry/exception/ChatInquiryErrorCode.java
  src/main/java/com/dnd/gongmuin/chat_inquiry/repository/ChatInquiryRepository.java
  src/main/java/com/dnd/gongmuin/chat_inquiry/service/ChatInquiryService.java
  src/test/java/com/dnd/gongmuin/chat_inquiry/service/ChatInquiryServiceTest.java
Labels: 🚨 fix

#230 [fix #229] JWT 관리 문제 해결
  src/main/java/com/dnd/gongmuin/auth/service/AuthService.java
  src/main/java/com/dnd/gongmuin/member/service/MemberService.java
  src/test/java/com/dnd/gongmuin/auth/service/AuthServiceTest.java
Labels: 🚨 fix, ✨ feat, ♻️ refactor
